browsersync:
  notify: true
  open:   false # set to true to open localhost:3000 in chrome browser upon execution of gulp command.
  port:   3000
  server:
    basedir: "_site/"
  xip:    false
  browser: "Google Chrome"

# Clean the jekyll _site/ build dir.
clean:
  - "_site" # clean these folders on execution of gulp command
#  - "_posts/*"

# Copy task coppies static assets like images into site build
# Any changes to Copy task should be also be made to travisCopy.
copy:
  # Paths to static assets that aren't (S)CSS or JavaScript
  # because these are completely handled by the sass and javascript tasks.
  assets:
    # all files below the assets dir, except the exclusions...
    - "assets/img/*"
    # exclusions: (Don't copy these items because they are handled by other gulp tasks)
    - "!assets/{js,scss,css}/**/*"   # js, scss and css files
    - "!assets/css{,/**}"            # css dir
    - "!assets/js{,/**}"             # js dir
    - "!assets/scss{,/**}"           # scss dir
  dist: "_site/assets/"
  notification: "Running Copy"

# Main Gulp Sass task (for main.css).
# Any changes to Sass should be also be made to travisSass.
sass:
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running Sass"
  src: "assets/scss/main.scss"

# Gulp task to create stylesheet for custom options in CloudCannon (CMS customizations). Editors can use these styles as option in the CMS.
cmsScss:
  outputStyle: {outputStyle: 'expanded'} # Pass an object w/ outputStyle: 'expanded' for CloudCanon custom stylesheet
  dest:
    jekyllRoot: "assets/css/"
    buildDir: "_site/assets/css/"
  notification: "Running cmsScss"
  src: "assets/scss/content.scss"

# Gulp task to create sitemap on production builds (`$ gulp --production`).
sitemap:
  src: # Defines what items should be in used in creating the sitemap.
    - "_site/*.html"
    - "_site/**/*.html"
    - "_site/**/**/*.html"
    - "_site/**/*.pdf" # Yes, PDF's too.
    - "_site/**/**/*.pdf"
  notification: "Running sitemap"
  siteUrl: "https://news.kcc.edu"

jekyll:
  notification: "Running jekyll"

watch: # 'Watch' for changes in all the following:
  images:
    - "assets/img/**/*"
    - "uploads/**/*"
  sass: "assets/scss/**/*.scss"
  cmsScss: "assets/scss/**/*.scss"
  pages:
    - "*.{md,html,yml,xml}"
    - "{_data,_includes,_layouts,_pages,_posts,_alerts}/**/*.{md,html,yml,xml}"
    - "archive/*"
    # All these subfolders are added because the watch task was not looking deep enough
    # !exlclusions:
    - "!sitemap.xml"
    - "!_site/**/*.*"
    - "!assets/**/*.*"
